### PR TITLE
Fix GitHub pages deploy issue

### LINKED ISSUE #1: change source links
In files  <code>index.html , css,js</code>, modify links so as github pages work properly, at present, they don't work.

### PR DESCRIPTION
**Pull request by jigar-sable**
Fixes #1
Source links updated and modify api for make it working when deploy on github pages.

### CODE REVIEW

**Comment by d4rkener** [comment]
Its good too but you should have added ../ instead of removing ./

**Comment by d4rkener** [comment]
I would recommend you to install relative path from vs code (if you're using it) extensions it will make your life easier

**Comment by jigar-sable** [comment]
> Its good too but you should have added ../ instead of removing ./

I know that we use it for local but for deploying on github pages we need to remove it to provide path access.

**Comment by d4rkener** [comment]
ohh I didn't knew that cuz I never deployed my websites on github. I always use netlify

**Comment by himanshu007-creator** [comment]
@jigar-sable , can you host github page from your repo and share the link so that we can see changes in action?!

**Review by himanshu007-creator — APPROVED** [review]
LGTM🎉

**Comment by himanshu007-creator** [comment]
Thanks @jigar-sable  for your contribution✨

**Pull request merged**
